### ISSUE TITLE
分别安装Snell和ShadowTLS后在Surge里这样直接使用吗？

### ISSUE THREAD

**Issue by TingTing1990** [Slotheve/Snell#2]
Snell+TLS = snell, x.x.x.x（vps的ip）, 端口, psk=psk, version=4, shadow-tls-password=密码, shadow-tls-sni=自定义域名:443, shadow-tls-version=3

PS：snell和stls的端口要一样？

谢谢！

**Comment by Slotheve** [comment]
依次安装完成就可以在surge使用了, 所有信息填入surge并将端口更改为stls的端口即可

**Comment by TingTing1990** [comment]
@Slotheve 非常感谢，之前我一路安装2个后用我上面的格式无论6666还是9999都测试time out，并没有切换去看网络，不知道是不是这个无法测试，我再切换到节点试试

**Comment by Slotheve** [comment]
shadow-tls-sni 域名不需要加443

**Comment by TingTing1990** [comment]
多谢
